### ISSUE TITLE
Sugestão: News colaborativa

### ISSUE THREAD

**Issue by theandersonn** [csscastshow/shows#1]
Vai ter news?  :open_mouth:
Deixa aberto aqui pra galera ajudar a montar o conteúdo com a indicação de links |o|

**Comment by afonsopacifer** [comment]
Criei a news sim.
Acho uma boa, mas como vc sugere, os e-mail não terão uma regularidade tipo, semanal, entao o que acha, abrir uma issue e depois que mandar o e-mail fechar, mas sem dar prazos?

**Comment by theandersonn** [comment]
Sim, poderia abrir a issue e referenciar a edição da news, depois de enviar abre uma nova... desta maneira vai ajudar a organizar as indicações.

**Comment by afonsopacifer** [comment]
@theandersonn no e-mail da news dessa semana eu vou falar sobre isso, para quem quiser mandar uma sugestão de conteúdo mandar por aqui =D, Vlw pela dica ;)

**Comment by theandersonn** [comment]
Tá falado, espero ter boas dicas pra colaborar :)
